DATASET:
  IMAGE_PATH: './data/original_images/'
  MASK_PATH: './data/label_images_semantic/'
  MODEL_PATH: './gdrive/MyDrive/segmentation/model/'
  PREDICT_PATH: './gdrive/MyDrive/segmentation/image/'

PARAM:
  NUM_CLASSES: 24
  BATCH_SIZE: 3
  INITIAL_LR: 1.0e-3
  EPOCH: 30
  STOP_EPOCH: 7
  WEIGHT_DECAY: 1.0e-4

PREPROCESS:
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]